import {useEffect,useState} from "react";import {Plus,Edit2,Trash2,Upload,Image as ImageIcon} from "lucide-react";import API from "../../services/api";
const empty={projectId:"",title:"",imageUrl:"",tag:"Site Update",description:"",date:"",source:"Camera",qualityVerified:true};const input={width:"100%",padding:"8px 10px",border:"1px solid #e2e8f0",borderRadius:6,fontSize:12,boxSizing:"border-box"};
export default function AdminGallery(){const[items,setItems]=useState([]),[projects,setProjects]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true);
const load=async()=>{setLoading(true);try{const[a,b]=await Promise.all([API.get("/gallery"),API.get("/projects")]);setItems(a.data.data||[]);setProjects(b.data.data||[])}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const file=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>10*1024*1024)return alert("Please choose an image below 10MB");const r=new FileReader();r.onload=()=>setForm(x=>({...x,imageUrl:r.result}));r.readAsDataURL(f)};
const save=async e=>{e.preventDefault();try{if(edit)await API.put(`/gallery/${edit}`,form);else await API.post("/gallery",form);setOpen(false);setEdit(null);setForm(empty);load()}catch(e){alert(e.response?.data?.message||"Save failed")}};
const start=r=>{setEdit(r._id);setForm({...r,projectId:r.projectId?._id||r.projectId});setOpen(true)};const del=async id=>{if(confirm("Delete this gallery item?")){await API.delete(`/gallery/${id}`);load()}};
return <><div className="welcome-section"><div><h1>Site Gallery Management 📸</h1><p>Upload, edit and delete project photos stored in MongoDB.</p></div><button className="date-button" style={{background:"#d97706",color:"#fff",border:"none"}} onClick={()=>{setEdit(null);setForm(empty);setOpen(true)}}><Plus size={15}/> Upload Photo</button></div>
<div className="dashboard-grid role-grid">{loading?<div className="dashboard-card">Loading...</div>:items.map(i=><div className="dashboard-card" key={i._id} style={{padding:0,overflow:"hidden"}}><img src={i.imageUrl} alt={i.title} style={{width:"100%",height:180,objectFit:"cover"}}/><div style={{padding:12}}><strong>{i.title}</strong><div style={{fontSize:11,color:"#64748b",margin:"5px 0"}}>{i.projectId?.name||"-"} • {i.source}</div><p style={{fontSize:11,color:"#64748b"}}>{i.description}</p><button className="menu-item" onClick={()=>start(i)}><Edit2 size={13}/> Edit</button><button className="menu-item" style={{color:"#dc2626"}} onClick={()=>del(i._id)}><Trash2 size={13}/> Delete</button></div></div>)}</div>
{open&&<div style={overlay}><div className="dashboard-card" style={{width:600,maxWidth:"95vw"}}><h3>{edit?"Edit Gallery Item":"Upload Gallery Photo"}</h3><form onSubmit={save} style={{display:"flex",flexDirection:"column",gap:12}}><label>Project<select required value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value})} style={input}><option value="">Select project</option>{projects.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select></label><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} style={input}/></label><label>Image File<input type="file" accept="image/*" onChange={file} style={input}/></label>{form.imageUrl&&<img src={form.imageUrl} alt="preview" style={{width:"100%",height:180,objectFit:"cover",borderRadius:8}}/>}<label>Image URL (optional)<input value={form.imageUrl.startsWith("data:")?"":form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..." style={input}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><label>Tag<input value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})} style={input}/></label><label>Source<select value={form.source} onChange={e=>setForm({...form,source:e.target.value})} style={input}>{["Camera","Drone","360 Tour"].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} style={{...input,minHeight:70}}/></label><label style={{fontSize:12}}><input type="checkbox" checked={form.qualityVerified} onChange={e=>setForm({...form,qualityVerified:e.target.checked})}/> Quality verified</label><div style={{display:"flex",justifyContent:"flex-end",gap:8}}><button type="button" className="date-button" onClick={()=>setOpen(false)}>Cancel</button><button className="date-button" style={{background:"#d97706",color:"#fff",border:"none"}}><Upload size={14}/> Save Photo</button></div></form></div></div>}</>}
const overlay={position:"fixed",inset:0,background:"rgba(15,23,42,.45)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:1000};
