const express = require("express");
const router = express.Router();
const { protect, authorize } = require("../middleware/authMiddleware");
const { getPayments, createPayment, updatePayment, deletePayment } = require("../controllers/paymentController");
router.use(protect);
router.get("/", getPayments);
router.post("/", authorize("admin", "project_manager"), createPayment);
router.put("/:id", authorize("admin", "project_manager"), updatePayment);
router.delete("/:id", authorize("admin"), deletePayment);
module.exports = router;
